### ISSUE TITLE
Crash on entering world

### ISSUE THREAD

**Issue by NielsPilgaard** [Leviathan143/LootTweaker#70]
**Describe the bug**
Crash on entering world.

**To Reproduce**

* Download the modpack Enigmatica 2: Expert v1.76
* Make a new world
* Find a loot chest
* Crash

**Expected behavior**
No crash.

**Logs & scripts**
Crash: https://pastebin.com/EhxRmvGf
CraftTweakerLog: https://gist.github.com/NillerMedDild/99ad8bc0fe1dcd4c01655fb5afe1014d
Script used: https://gist.github.com/NillerMedDild/e0202f1bc0455c9eabec6f9d8e7fc61e

**Version Info (Exact versions only):**
LootTweaker: 0.1.5+MC1.12.2
CraftTweaker/Minetweaker: 1.12-4.1.19
Forge: 1.12.2-14.23.5.2847
Minecraft: 1.12.2

**Additional context**
I believe this crash only happens when near a loot chest.

**Comment by Daomephsta** [comment]
I downloaded E2E 1.76 & tried to reproduce this with spawned in chests using the loot tables your script modifies, as well as some structure chests I found (mineshaft, AS fountain, and quark pirate ship). Neither getting near to, nor opening any of them caused a crash. They all worked as I expected them to.

**Comment by Daomephsta** [comment]
I tried reloading the world while near a test chest, then opening it; as well as switching to another world and back while near a test chest, then opening it. Neither reproduced the crash.

I'll need you to narrow down the reproduction criteria before I can do anything more.

**Comment by NielsPilgaard** [comment]
Alright, thanks for testing - I'll just close this since it can't be reproduced :)

**Comment by Daomephsta** [comment]
Reopening because I've got 2 other reports of this issue. Something's up.

**Comment by SandwichHorror** [comment]
I am also getting this crash and am having trouble getting around it other than entirely removing the loottweaker scripts in the first place.

**Comment by Dakedres** [comment]
Same issue here when running Rebirth of The Night with some extra mods (and some removed, namely Ice and Fire). I note that because the unmodified version does not crash. This leads me to believe it's some issue between LootTweaker and another mod, and if it is, it might be worthwhile to investigate which mods are shared between all of the instances of this happening.

[Modlist](https://gist.github.com/Dakedres/9e7bc40f990a5a1df734a7bfc6f967e4) (ripped from the crash log because lazy)
[Mods Added/Removed](https://gist.github.com/Dakedres/43c0c1d623a9632b06bbfa35df4f2ad1)

Note that any recipes in the pack refrencing items that don't exist anymore (due to some mods being removed) have been fixed, yes, I'm sure, I've checked it several times over.

**Comment by Daomephsta** [comment]
Please reproduce the issue with [this debug build](https://drive.google.com/open?id=1hrIIiufdX4etq-gs2cj1rx2Cb4-EY8bC), it'll crash differently and spit out a CT error. These will help me find the source of the issue.

**Comment by Daomephsta** [comment]
@Dakedres @NillerMedDild 
Had any time to test with the debug build? I'd really like to get this fixed. It's clearly a problem, but I currently have no idea why what's happening is happening.

**Comment by NielsPilgaard** [comment]
I'm afraid not, no :/

**Comment by a-frenzy** [comment]
Seems to be working for me with the debug build, thanks

**Comment by Daomephsta** [comment]
@frenzye 
The debug build doesn't fix anything, it makes the error more informative for me.

**Comment by Daomephsta** [comment]
Encountered this issue while debugging another. I was finally able to debug and fix it.

**Comment by NielsPilgaard** [comment]
Awesome, thanks!
