### ISSUE TITLE
Skipped modifying pool because it is frozen

### ISSUE THREAD

**Issue by GEM988** [Leviathan143/LootTweaker#71]
I have created a script file to remove almost all loot added by IC2, the script appears to run properly but at the end of the crafttweaker log I get the line:

"[AVAILABLE][CLIENT][INFO] Skipped modifying pool ic2 of table minecraft:chests/desert_pyramid because it is frozen"

The loot is still in the desert temples when I create a new world and check one.

**To Reproduce**
This is the script that I have written is here https://pastebin.com/hK0xknfN

**Expected behavior**
i expected to loot to no longer spawn in the chests of the Desert Temple.

**Logs & scripts**
CraftTweaker.log file is here https://pastebin.com/h6q0U2M0

**Version Info (Exact versions only):**
LootTweaker: 0.1.5
CraftTweaker/Minetweaker: Crafttweaker 4.1.20
Forge: 14.23.5.2847
Minecraft: 1.12.2

**Comment by Daomephsta** [comment]
This issue is caused by a bug in IC2, which I reported a while ago ([issue tracker entry](https://bt.industrial-craft.net/view.php?id=2433)).

You can work around the bug by removing the pool; adding a new pool with the same rolls and bonus rolls; then adding any loot you want to keep to the new pool.
