### ISSUE TITLE
0.3.2 Crash on world load

### ISSUE THREAD

**Issue by Foreck1** [Leviathan143/LootTweaker#93]
**Describe the bug**
Crash on load on a heavily modded instance (rebirth of the night in dev version)

**To Reproduce**
- Load the game normally
- Try to load world

**Expected behavior**
Not to crash

**Logs & scripts**
[crash log](https://mclo.gs/lFMM3KY)

**Version Info (Exact versions only):**
LootTweaker: 0.3.2+MC1.12.2
CraftTweaker/Minetweaker: 1.12-4.1.20.698
Forge: 14.23.5.2859 (recommended)
Minecraft: 1.12.2

**Additional context**
List of mods is included in the log; however, it's worth mentioning there are several mixin and performance mods all stacked together, as expected of a huge mod pack.

**Comment by Daomephsta** [comment]
I think this is the same issue as #92, but I can't tell because the crash report truncates the error right where it starts to get useful

**Comment by Daomephsta** [comment]
I've found and corrected the bug (4a567e66917cd28672ecc7b9b04ebf881de0a05e), then altered the code so it's extremely unlikely that kind of bug can happen again.
0.3.3 is now available on CurseForge with the fix.
<https://www.curseforge.com/minecraft/mc-mods/loottweaker/files/5092247>

I'm leaving this issue open because I'm not totally sure it's the same as #92. Please try 0.3.3 and close this issue if it fixes the crash,

**Comment by Daomephsta** [comment]
It's been a month with no further response. I'll assume this was the same as #92 and close it in 7 days, unless I receive information otherwise.
