### ISSUE TITLE
Crash w/ LevelUp

### ISSUE THREAD

**Issue by Shivaxi** [Leviathan143/LootTweaker#96]
LevelUp throws a crash when LootTweaker is updated to the latest version 0.4.0

[crash-2024-06-10_17.53.26-client.txt](https://github.com/user-attachments/files/15779680/crash-2024-06-10_17.53.26-client.txt)

No issues on 0.3.1 or 0.3.3.  We use an old version of LevelUp, but we tested with the latest version of LevelUp and the same crash still occurs.  Tried with only LevelUp and LootTweaker 0.4.0 installed, crash occurs.

**Comment by Daomephsta** [comment]
This is the same root issue as #94. LootTweaker is trying to log fixed issues with a loot table, but due to an oversight on my part, some of the information it needs doesn't exist in cases like this, so it crashes. 
I think in this specific case there might not be an issue with the table at all, but LT thinks there is due to another oversight.
The issue has been fixed in-dev. I'll make a release tomorrow.

Note that LevelUp uses the custom flag for its config loot tables, which means Forge does not fire the loot table event for them. Thus you can't edit them with LootTweaker.
