### ISSUE TITLE
Any plans to add a mod to Modrinth?

### ISSUE THREAD

**Issue by Alter73** [Leviathan143/LootTweaker#97]
Hi! I just make quite a lot of modpacks in the Modrinth launcher and a lot of mods have moved there. It is also possible because the service is developed only for Minecraft. It would be much more convenient if LootTweaker addon was also in Modrinth, otherwise I have to download it separately for each modpack and check for its updates, but this is very inconvenient when creating modpacks. It would be nice if such a cool addon could be downloaded from the second most popular Minecraft modding site.

**Comment by Daomephsta** [comment]
Yeah sure. I like Modrinth, so knowing someone would have use for LT being on Modrinth is all the additional reason I need.

**Comment by Daomephsta** [comment]
It's pending moderator approval at https://modrinth.com/mod/loottweaker, only the latest version for MC 1.12.2 is uploaded. 
If anyone wants the latest 1.11 or 1.10 versions on Modrinth too, ask and I'll upload those as well. Won't upload otherwise because they're old and I don't support them, unlike the latest 1.12.2 version.

**Comment by Alter73** [comment]
Well, I'm glad to hear that. You will really help a lot. Yes, if it doesn't bother you, then add versions for 1.10 and 1.11. I think there are a lot of people who will need these versions. I'll be waiting for the mod to be released on Modrinth! Thanks for the reply!

**Comment by Daomephsta** [comment]
It's been approved, and I've added the latest 1.10 and 1.11 versions
